# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PycharmProjects\freetubedownloader\static\QtUI\freetubedownloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 620)
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 780, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.linksEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.linksEdit.setGeometry(QtCore.QRect(10, 50, 780, 420))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.linksEdit.setFont(font)
        self.linksEdit.setPlainText("")
        self.linksEdit.setPlaceholderText("Paste URLs here")
        self.linksEdit.setObjectName("linksEdit")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 530, 781, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.ButtonsLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.ButtonsLayout.setContentsMargins(0, 0, 0, 0)
        self.ButtonsLayout.setObjectName("ButtonsLayout")
        self.VideoButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.VideoButton.setObjectName("VideoButton")
        self.ButtonsLayout.addWidget(self.VideoButton)
        self.AudioButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.AudioButton.setObjectName("AudioButton")
        self.ButtonsLayout.addWidget(self.AudioButton)
        self.OutEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.OutEdit.setGeometry(QtCore.QRect(10, 480, 630, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OutEdit.setFont(font)
        self.OutEdit.setReadOnly(True)
        self.OutEdit.setObjectName("OutEdit")
        self.BrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseButton.setGeometry(QtCore.QRect(650, 480, 140, 40))
        self.BrowseButton.setObjectName("BrowseButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("VAG World")
        font.setBold(True)
        font.setWeight(75)
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FreeTubeDownloader"))
        self.label.setText(_translate("MainWindow", "Free YouTube Downloader"))
        self.VideoButton.setText(_translate("MainWindow", "Video"))
        self.AudioButton.setText(_translate("MainWindow", "Audio"))
        self.OutEdit.setPlaceholderText(_translate("MainWindow", "Output directory"))
        self.BrowseButton.setText(_translate("MainWindow", "Browse"))
